version: "3"

services:

  web-api:
    hostname: web-api
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env
    command: ["python", "./api/api.py"]

  ranks:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
    command: ["python", "./ranks/service.py"]
    depends_on:
      - web-api
    links:
      - web-api

  prices:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
    command: ["python", "./prices/service.py"]
    depends_on:
      - web-api
    links:
      - web-api